name: mi.municipio
description: Micro-servicios de la gestión municipal destinados vecinos de la comunidad.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  #google_maps_flutter: ^0.5.11+1
  #location: ^2.3.5   #lo uso para obtener mas facil la locación actual ya que con geolocator me resultó mas complicado
  #geolocator: ^5.3.0 #lo uso para calcular cercania ya que con location no se como es
  #http: ^0.12.0
  #bubble: ^1.1.0
  #percent_indicator: ^2.1.1
  #image_picker: ^0.6.2+3
  #flutter_open_whatsapp: ^0.1.2
  font_awesome_flutter: ^8.11.0
  #firebase_auth: ^0.20.0+1
  #google_sign_in: ^4.5.9
  #firebase_storage: ^2.1.0
  #cloud_firestore: ^0.9.13
  #generic_bloc_provider: ^1.1.0
  #flutter_facebook_login: ^3.0.0
  #provider: ^4.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-complete-ios.png"
  image_path_android: "assets/images/logo-complete-ios.png"
  image_path_ios: "assets/images/logo-complete-ios.png"
  adaptive_icon_background: "assets/images/ico-bg.png"
  adaptive_icon_foreground: "assets/images/logo-white-into-circle.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/images/logo-complete.png
    - assets/images/logo-color.png
    - assets/images/logo-white.png
    - assets/images/logo-bg.png
    - assets/images/logo-white-into-circle.png

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/IcoMoon.ttf